[
  {
    "line": "North South Line",
    "stations": [
      {"name": "Jurong East", "code": "NS1"},
      {"name": "Bukit Batok", "code": "NS2"},
      {"name": "Bukit Gombak", "code": "NS3"},
      {"name": "Choa Chu Kang", "code": "NS4"},
      {"name": "Yew Tee", "code": "NS5"},
      {"name": "Kranji", "code": "NS7"},
      {"name": "Marsiling", "code": "NS8"},
      {"name": "Woodlands", "code": "NS9"},
      {"name": "Admiralty", "code": "NS10"},
      {"name": "Sembawang", "code": "NS11"},
      {"name": "Canberra", "code": "NS12"},
      {"name": "Yishun", "code": "NS13"},
      {"name": "Khatib", "code": "NS14"},
      {"name": "Yio Chu Kang", "code": "NS15"},
      {"name": "Ang Mo Kio", "code": "NS16"},
      {"name": "Bishan", "code": "NS17"},
      {"name": "Braddell", "code": "NS18"},
      {"name": "Toa Payoh", "code": "NS19"},
      {"name": "Novena", "code": "NS20"},
      {"name": "Newton", "code": "NS21"},
      {"name": "Orchard", "code": "NS22"},
      {"name": "Somerset", "code": "NS23"},
      {"name": "Dhoby Ghaut", "code": "NS24"},
      {"name": "City Hall", "code": "NS25"},
      {"name": "Raffles Place", "code": "NS26"},
      {"name": "Marina Bay", "code": "NS27"},
      {"name": "Marina South Pier", "code": "NS28"}
    ],
    "operator": "SMRT"
  },
  {
    "line": "East West Line",
    "stations": [
      {"name": "Pasir Ris", "code": "EW1"},
      {"name": "Tampines", "code": "EW2"},
      {"name": "Simei", "code": "EW3"},
      {"name": "Tanah Merah", "code": "EW4"},
      {"name": "Bedok", "code": "EW5"},
      {"name": "Kembangan", "code": "EW6"},
      {"name": "Eunos", "code": "EW7"},
      {"name": "Paya Lebar", "code": "EW8"},
      {"name": "Aljunied", "code": "EW9"},
      {"name": "Kallang", "code": "EW10"},
      {"name": "Lavender", "code": "EW11"},
      {"name": "Bugis", "code": "EW12"},
      {"name": "City Hall", "code": "EW13"},
      {"name": "Raffles Place", "code": "EW14"},
      {"name": "Tanjong Pagar", "code": "EW15"},
      {"name": "Outram Park", "code": "EW16"},
      {"name": "Tiong Bahru", "code": "EW17"},
      {"name": "Redhill", "code": "EW18"},
      {"name": "Queenstown", "code": "EW19"},
      {"name": "Commonwealth", "code": "EW20"},
      {"name": "Buona Vista", "code": "EW21"},
      {"name": "Dover", "code": "EW22"},
      {"name": "Clementi", "code": "EW23"},
      {"name": "Jurong East", "code": "EW24"},
      {"name": "Chinese Garden", "code": "EW25"},
      {"name": "Lakeside", "code": "EW26"},
      {"name": "Boon Lay", "code": "EW27"},
      {"name": "Pioneer", "code": "EW28"},
      {"name": "Joo Koon", "code": "EW29"},
      {"name": "Gul Circle", "code": "EW30"},
      {"name": "Tuas Crescent", "code": "EW31"},
      {"name": "Tuas West Road", "code": "EW32"},
      {"name": "Tuas Link", "code": "EW33"},
      {"name": "Expo", "code": "CG1"},
      {"name": "Changi Airport", "code": "CG2"}
    ],
    "operator": "SMRT"
  },
  {
    "line": "North East Line",
    "stations": [
      {"name": "HarbourFront", "code": "NE1"},
      {"name": "Outram Park", "code": "NE3"},
      {"name": "Chinatown", "code": "NE4"},
      {"name": "Clarke Quay", "code": "NE5"},
      {"name": "Dhoby Ghaut", "code": "NE6"},
      {"name": "Little India", "code": "NE7"},
      {"name": "Farrer Park", "code": "NE8"},
      {"name": "Boon Keng", "code": "NE9"},
      {"name": "Potong Pasir", "code": "NE10"},
      {"name": "Woodleigh", "code": "NE11"},
      {"name": "Serangoon", "code": "NE12"},
      {"name": "Kovan", "code": "NE13"},
      {"name": "Hougang", "code": "NE14"},
      {"name": "Buangkok", "code": "NE15"},
      {"name": "Sengkang", "code": "NE16"},
      {"name": "Punggol", "code": "NE17"}
    ],
    "operator": "SMRT"
  },
  {
    "line": "Circle Line",
    "stations": [
      {"name": "Dhoby Ghaut", "code": "CC1"},
      {"name": "Bras Basah", "code": "CC2"},
      {"name": "Esplanade", "code": "CC3"},
      {"name": "Promenade", "code": "CC4"},
      {"name": "Nicoll Highway", "code": "CC5"},
      {"name": "Stadium", "code": "CC6"},
      {"name": "Mountbatten", "code": "CC7"},
      {"name": "Dakota", "code": "CC8"},
      {"name": "Paya Lebar", "code": "CC9"},
      {"name": "MacPherson", "code": "CC10"},
      {"name": "Tai Seng", "code": "CC11"},
      {"name": "Bartley", "code": "CC12"},
      {"name": "Serangoon", "code": "CC13"},
      {"name": "Lorong Chuan", "code": "CC14"},
      {"name": "Bishan", "code": "CC15"},
      {"name": "Marymount", "code": "CC16"},
      {"name": "Caldecott", "code": "CC17"},
      {"name": "Botanic Gardens", "code": "CC19"},
      {"name": "Farrer Road", "code": "CC20"},
      {"name": "Holland Village", "code": "CC21"},
      {"name": "Buona Vista", "code": "CC22"},
      {"name": "one-north", "code": "CC23"},
      {"name": "Kent Ridge", "code": "CC24"},
      {"name": "Haw Par Villa", "code": "CC25"},
      {"name": "Pasir Panjang", "code": "CC26"},
      {"name": "Labrador Park", "code": "CC27"},
      {"name": "Telok Blangah", "code": "CC28"},
      {"name": "HarbourFront", "code": "CC29"},
      {"name": "Bayfront", "code": "CE1"},
      {"name": "Marina Bay", "code": "CE2"}
    ],
    "operator": "SMRT"
  },
  {
    "line": "Downtown Line",
    "stations": [
      {"name": "Bukit Panjang", "code": "DT1"},
      {"name": "Cashew", "code": "DT2"},
      {"name": "Hillview", "code": "DT3"},
      {"name": "Beauty World", "code": "DT5"},
      {"name": "King Albert Park", "code": "DT6"},
      {"name": "Sixth Avenue", "code": "DT7"},
      {"name": "Tan Kah Kee", "code": "DT8"},
      {"name": "Botanic Gardens", "code": "DT9"},
      {"name": "Stevens", "code": "DT10"},
      {"name": "Newton", "code": "DT11"},
      {"name": "Little India", "code": "DT12"},
      {"name": "Rochor", "code": "DT13"},
      {"name": "Bugis", "code": "DT14"},
      {"name": "Promenade", "code": "DT15"},
      {"name": "Bayfront", "code": "DT16"},
      {"name": "Downtown", "code": "DT17"},
      {"name": "Telok Ayer", "code": "DT18"},
      {"name": "Chinatown", "code": "DT19"},
      {"name": "Fort Canning", "code": "DT20"},
      {"name": "Bencoolen", "code": "DT21"},
      {"name": "Jalan Besar", "code": "DT22"},
      {"name": "Bendemeer", "code": "DT23"},
      {"name": "Geylang Bahru", "code": "DT24"},
      {"name": "Mattar", "code": "DT25"},
      {"name": "MacPherson", "code": "DT26"},
      {"name": "Ubi", "code": "DT27"},
      {"name": "Kaki Bukit", "code": "DT28"},
      {"name": "Bedok North", "code": "DT29"},
      {"name": "Bedok Reservoir", "code": "DT30"},
      {"name": "Tampines West", "code": "DT31"},
      {"name": "Tampines", "code": "DT32"},
      {"name": "Tampines East", "code": "DT33"},
      {"name": "Upper Changi", "code": "DT34"},
      {"name": "Expo", "code": "DT35"}
    ],
    "operator": "SBS Transit"
  },
  {
    "line": "Thomson–East Coast Line",
    "stations": [
      {"name": "Woodlands North", "code": "TE1"},
      {"name": "Woodlands", "code": "TE2"},
      {"name": "Woodlands South", "code": "TE3"},
      {"name": "Springleaf", "code": "TE4"},
      {"name": "Lentor", "code": "TE5"},
      {"name": "Mayflower", "code": "TE6"},
      {"name": "Bright Hill", "code": "TE7"},
      {"name": "Upper Thomson", "code": "TE8"},
      {"name": "Caldecott", "code": "TE9"},
      {"name": "Stevens", "code": "TE10"},
      {"name": "Napier", "code": "TE12"},
      {"name": "Orchard Boulevard", "code": "TE13"},
      {"name": "Orchard", "code": "TE15"},
      {"name": "Great World", "code": "TE15"},
      {"name": "Havelock", "code": "TE16"},
      {"name": "Outram Park", "code": "TE18"},
      {"name": "Maxwell", "code": "TE18"},
      {"name": "Shenton Way", "code": "TE19"},
      {"name": "Marina Bay", "code": "TE20"},
      {"name": "Gardens by the Bay", "code": "TE22"},
      {"name": "Tanjong Rhu", "code": "TE23"},
      {"name": "Katong Park", "code": "TE24"},
      {"name": "Tanjong Katong", "code": "TE25"},
      {"name": "Marine Parade", "code": "TE26"},
      {"name": "Marine Terrace", "code": "TE27"},
      {"name": "Siglap", "code": "TE28"},
      {"name": "Bayshore", "code": "TE29"}
    ],
    "operator": "SBS Transit"
  },
  {
    "line": "Bukit Panjang LRT",
    "stations": [
      {"name": "Choa Chu Kang", "code": "BP1"},
      {"name": "South View", "code": "BP2"},
      {"name": "Keat Hong", "code": "BP3"},
      {"name": "Teck Whye", "code": "BP4"},
      {"name": "Phoenix", "code": "BP5"},
      {"name": "Bukit Panjang", "code": "BP6"},
      {"name": "Petir", "code": "BP7"},
      {"name": "Pending", "code": "BP8"},
      {"name": "Bangkit", "code": "BP9"},
      {"name": "Fajar", "code": "BP10"},
      {"name": "Segar", "code": "BP11"},
      {"name": "Jelapang", "code": "BP12"},
      {"name": "Senja", "code": "BP13"},
      {"name": "Ten Mile Junction", "code": "BP14"}
    ],
    "operator": "SBS Transit"
  },
  {
    "line": "Sengkang LRT",
    "loops": {
      "North Loop": [
        {"name": "Compassvale", "code": "SE1"},
        {"name": "Rumbia", "code": "SE2"},
        {"name": "Bakau", "code": "SE3"},
        {"name": "Kangkar", "code": "SE4"},
        {"name": "Ranggung", "code": "SE5"}
      ],
      "South Loop": [
        {"name": "Cheng Lim", "code": "SW1"},
        {"name": "Farmway", "code": "SW2"},
        {"name": "Kupang", "code": "SW3"},
        {"name": "Thanggam", "code": "SW4"},
        {"name": "Fernvale", "code": "SW5"},
        {"name": "Layar", "code": "SW6"},
        {"name": "Tongkang", "code": "SW7"},
        {"name": "Renjong", "code": "SW8"}
      ]
    },
    "operator": "SBS Transit"
  },
  {
    "line": "Punggol LRT",
    "loops": {
      "East Loop": [
        {"name": "Punggol", "code": "PE1"},
        {"name": "Cove", "code": "PE2"},
        {"name": "Meridian", "code": "PE3"},
        {"name": "Coral Edge", "code": "PE4"},
        {"name": "Riviera", "code": "PE5"},
        {"name": "Kadaloor", "code": "PE6"},
        {"name": "Oasis", "code": "PE7"},
        {"name": "Damai", "code": "PE8"}
      ],
      "West Loop": [
        {"name": "Punggol", "code": "PW1"},
        {"name": "Sam Kee", "code": "PW2"},
        {"name": "Teck Lee", "code": "PW3"},
        {"name": "Punggol Point", "code": "PW4"},
        {"name": "Samudera", "code": "PW5"},
        {"name": "Nibong", "code": "PW6"},
        {"name": "Sumang", "code": "PW7"},
        {"name": "Soo Teck", "code": "PW8"}
      ]
    },
    "operator": "SBS Transit"
  }
]